package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"funovation_23/graph/model"
	"funovation_23/internal/util"
)

// ProcessYoutubeVideo is the resolver for the processYoutubeVideo field.
func (r *mutationResolver) ProcessYoutubeVideo(ctx context.Context, url string) (*model.Ack, error) {
	videoID := util.GetYoutubeIDFromURL(url)
	err := r.VideoUsecase.ProcessYoutubeVideo(videoID)
	if err != nil {
		return nil, err
	}
	return &model.Ack{Ok: true}, nil
}
