// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ack struct {
	Ok bool `json:"ok"`
}

type Clip struct {
	ID        string `json:"Id"`
	VideoID   string `json:"VideoId"`
	Thumbnail string `json:"thumbnail"`
	URL       string `json:"url"`
}

type Reel struct {
	ID      string `json:"id"`
	VideoID string `json:"videoId"`
	URL     string `json:"URL"`
}

type ReelRequest struct {
	VideoID string   `json:"videoId"`
	ClipIds []string `json:"clipIds"`
}

type VideoRequest struct {
	URL         string `json:"url"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type VideoResponse struct {
	ID          string  `json:"id"`
	URL         string  `json:"url"`
	Title       string  `json:"title"`
	YouTubeID   string  `json:"youTubeId"`
	Status      string  `json:"status"`
	Thumbnail   string  `json:"thumbnail"`
	CustomTitle string  `json:"customTitle"`
	Description string  `json:"description"`
	Clips       []*Clip `json:"clips"`
}
