apiVersion: v1
kind: Pod
metadata: 
  name: funovation
  lables:
    app: funovation
spec:
  initContainers:
    - name: funovation-migrations
      image: funovation-migrations
      command: [ "/app/run_migrations" ]
      env:
        - name: SERVICE_NAME
          value: funovation-migrations
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgresql-funovation:5432/funovation?sslmode=disable"
  containers:
    - name: funovation
      image: funovation
      ports:
        - containerPort: 8080
      env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgresql-funovation:5432/funovation?sslmode=disable"